-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgU/UTny2s+j9/RRmS
VWEWgTkkFOkxHa23I6hTGwEufnGgCgYIKoZIzj0DAQehRANCAASqBzOAeFElpXMC
/U+WxFLlzImbKyI2voCr9CDaCQCiA5NZlWJNQVtZlZq74lcBHzeSPTy+JbzHcKd+
wMaKJ6Sp
-----END PRIVATE KEY-----